### ISSUE TITLE
1.lekce úkoly

### ISSUE THREAD

**Issue by urbanovaklara** [urbanovaklara/python-012021#1]
Ahoj @pesikj ,

prosím o kontrolu řešení zadaných příkladů. Není u příkladu č.5 chyba v zadání? Neměly by být klíče ve slovníku jedinečné? Pokud ne, řešení ještě doupravím.
Děkuju

Klára

**Comment by pesikj** [comment]
Ahoj Kláro,

### 1. úkol :heavy_check_mark:

Super :-)
​
### 2. úkol :heavy_check_mark:

- U poslední větve bych dal jen `else`, podmínka je tak přehlednější.
- Pokud by zákazník požadoval přesně to množství, které je na skladě, tak se nestane nic. To pomocí `else` vyřešíš, i když zpráva pro uživatele nebude přesná.
​
### 3. úkol :heavy_check_mark:

Správně :-)
​
### 4. úkol :heavy_check_mark:
Zápis s dvoutečkou a příkazem `morse += morseCode[p]` na jednom řádku sice funguje, ale určitě by to chtělo dát příkaz na další řádek. Plus ten znak lomítka by neměl být "přeložený" do Morseovky, ale vložený do textu (např. aby člověk věděl, kdy má udělat pauzu v blikání baterkou).
```python
for p in slovo:
    if p == " ":
        morse += "/"
    else:
        morse += morseCode[p]
```
Pokud tě zajímají zkrácené zápisy, tak Python umí zapsat podmínku i na jeden řádek, to by vypadalo takto:
```python
for p in slovo:
    morse += morseCode["/"] if p == " " else morseCode[p]​
```
Na začátku je hodnota, která se vloží v případě, že je podmínka splněná. Za slovem `if` je podmínka a za `else` hodnota, která se vloží, pokud podmínka není splněná.

### 5. úkol :heavy_check_mark:
Ta samá připomínka jako ve 4 :-) Můžeš si vyzkoušet vložit jednořádkovou podmínku podle příkladu výše.

V zadání je chyba, ale teoreticky by nemusela být. Název knihy totiž nemusí být unikátní "identifikátor", např. by nakladatelství mohlo stejnou knihu vydat jako papírovou i elektronickou ve stejném roce a pak by evidovala dvakrát její prodeje. O tom si trochu více probereme, až budeme pracovat s indexy v `pandas`.
​
Shrnuti + pozadavky na upravu
​
Všechno jsou to drobnosti, takže ti za příklady píšu 5 bodů. Skvělá práce 👍
