### ISSUE TITLE
2.lekce úkoly

### ISSUE THREAD

**Issue by urbanovaklara** [urbanovaklara/python-012021#2]
Ahoj @pesikj,

díky za kontrolu předešlých úkolů, upravila jsem podle připomínek.
Prosím o kontrolu úkolů 6 až 7 + 10 z 2. lekce, s příkladem 9 jsem si nakonec nevěděla rady.
Díky

Klára

**Comment by pesikj** [comment]
### 6. úkol :heavy_check_mark:

Super, ten výpis s řetězcem je elegantní řešení, líbí se mi.
​
### 7. úkol :heavy_check_mark:
​
Taky super. Jen prosím nepiš názvy proměnných s velkým písmenem, po dnešní lekci je asi jasné, proč to tak nemá být :-)
​
### 8. úkol :heavy_check_mark:
​
Taky výborné.
​
### 9. úkol

Trochu jsem tvůj kód upravil, protože myšlenka je tam dobrá. Pokud chceš získat hodnoty ze slovníku jako seznam, tak to jde, to dělá řádek `item = list(item.values())`. Nyní můžeš pracovat s `item` jako se seznamem, na indexu 0 máš jméno a na vyšších indexech známky. Nyní by ti stačilo podmínku, která ověří průměr a která zkontroluje, jestli tam není žádná pětka (tj. propadnutí) nebo trojka (není možné vyznamenání). Např. ještě můžeš použít funkci max, která ti dá nejvyšší známku.

```python
prumerZnamek=0
for item in vysledky:
  item = list(item.values())
  prumerZnamek=(item[1]+item[2]+item[3]+item[4]+item[5]) / 5
  nejvyssZnamka=max(item[1],item[2],item[3],item[4],item[5])
  print(item[0],prumerZnamek)

```
​
### 10. úkol :heavy_check_mark:
​
Super
​
Shrnuti + pozadavky na upravu
​
Určitě zasloužené 4 body, ale zkus se prosím na chvilku podívat na 9. příklad a snad to bude za plný počet :-)
