### ISSUE TITLE
3. - 4. lekce úkoly

### ISSUE THREAD

**Issue by urbanovaklara** [urbanovaklara/python-012021#3]
Ahoj Jirko,

prosím o kontrolu úkolů 11 až 20 z třetí a čtvrté lekce.
Moc díky a hezký večer

Klára

**Comment by pesikj** [comment]
### Příklad 11

Super

### Příklad 12

Taky super :-)

### Příklad 13

Ve funkci `__init__()` nepotřebuješ parametr `volne`, protože jeho hodnotu stejně nepoužíváš, atribut vždy nastavíš na `True`.  Definice funkce tedy stačí takto:

```python
def __init__(self, vozidlo, regZnacka, pocetKilometru):
```

Dále ve funkci `vrat_auto()` nemusíš hodnotu parametru `pocetDni` ukládat jako atribut, protože ta hodnota je jen jednorázová a mimo tuto funkci už ji nepotřebuješ. Využití by např. mělo, pokud by sis kvůli statistice evidovala celkový počet dní, kdy bylo auto půjčené, takže bys pří vrácení tyto dny vždy připočetla k nějakému atributu. Navíc tam máš zbytečně dva parametry - `stavTachometru` a `pocetKilometru`. Já bych rozlišoval mezi stavem tachometru (tj. kolik má auto najeto celkem) a počtem km, které najel konkrétní zákazník. Počet km, které najel zákazník, pak přičteš ke stavu tachometru.

```python

class Auto:
    def get_info(self):
        return f"Jedná se o {self.vozidlo} s registrační značkou {self.regZnacka} a má najeto {self.stavTachometru}. Volne:{self.volne}"

    def __init__(self, vozidlo, regZnacka, stavTachometru):
        self.vozidlo=vozidlo
        self.regZnacka=regZnacka
        self.stavTachometru=stavTachometru
        self.volne=True

    def pujc_auto(self):
        if self.volne:
            self.volne = False
            return "Potvrzuji zapůjčení vozidla."
        else:
            return "Vozidlo není k dispozici."
    def vrat_auto(self, pocetKilometru, pocetDni):
        self.volne = True
        self.stavTachometru += pocetKilometru

        if pocetDni <= 7:
            return f"Cena za půjčení auta je {pocetDni * 400} Kč."
        else:
            return f"Cena za půjčení auta je {pocetDni * 300} Kč."

```

Jinak je to naprogramované moc hezky :-)

### Příklad 14

Super :-)

### Příklad 15

Podmínky lze zapsat jednodušeji:

- První podmínka zachytí případy, že je letní kino v daném termínu zavřené.
- Druhá podmínka zachytí případ, že jde o dražší termín. Tady už nemusíš kontrolovat, zda je kino otevřené, protože případ zavřeného kina zachytí první podmínka.
- A nakonec stačí `else`, protože všechny ostatní případy jsme už zachytili výše.

```python

if datumNavstevy < datetime(2021, 7, 1) or datumNavstevy > datetime(2021, 8, 31):
    print("V této době je letní kino zavřené.")
elif datumNavstevy <= datetime(2021, 8, 10):
    pocetOsob = int(input("Zadejte počet lístků."))
    cenaCelkem = pocetOsob * 250
    print (f"Celková cena za vstupenky je {cenaCelkem}")
else:
    pocetOsob = int(input("Zadejte počet lístků."))
    cenaCelkem = pocetOsob * 180
    print (f"Celková cena za vstupenky je {cenaCelkem}")

```

### Shrnutí

Příklady máš naprogramované moc hezky, ty poznámky jsou spíše detaily, super práce :-) Za lekci 3 připisuji 5 bodů.

**Comment by pesikj** [comment]
### Příklad 16

Super :-)

### Příklad 17

Super :-)

### Příklad 18

Super, jen zápis z pohovoru musíš uložit jako atribut :-)

```python
            self.zapis_z_pohovoru = input("Vložte zápis z pohovoru:")
```

### Příklad 19

Super :-)

### Příklad 20

Taky super.

### Shrnutí

Všechny příklady jsou moc hezky naprogramované, připisuji 5 bodů :-)
