### ISSUE TITLE
6 lekce úkoly

### ISSUE THREAD

**Issue by urbanovaklara** [urbanovaklara/python-012021#4]
Ahoj Jirko,

prosím o kontrolu úkolů k 6. lekci. 
Děkuju.

Klára

**Comment by pesikj** [comment]
Ahoj Kláro,

### Příklad 26

Super :-)

### Příklad 27

Super :-)

### Příklad 28

Super :-)

### Příklad 29

Taky super :-)

### Příklad 30

Taky super :-)

### Shrnutí

Připisuji 5 bodů :-)
