### ISSUE TITLE
7. lekce úkoly

### ISSUE THREAD

**Issue by urbanovaklara** [urbanovaklara/python-012021#5]
Ahoj Jirko,

prosím o kontrolu úkolů ze 7. lekce. Nevím, zda ten poslední nemám moc překombinovaný, asi by to šlo napsat jednodušeji?
Děkuji

Klára

**Comment by pesikj** [comment]
Ahoj Kláro,

### Úkol 31

Vypisuješ pouze 4 města, níže je oprava na 5 měst. :-) Jinak je to správně.

```python
print(teploty_odmaz.iloc[:5])
print(teploty_odmaz.iloc[-5:])
```

### Úkol 32

Super :-)

### Úkol 33

Super :-)

### Úkol 34

Super :-)

### Úkol 35

Překombinované to určitě není a v rámci toho, co jsme probírali, je to napsané správně. Pokud tě ale zajímá jednodušší zápis, můžeš použít funkci `pivot_table`, která dělá to samé, co kontingenční tabulka v Excelu - překlopí jeden sloupec na více :-) Více popsané s příklady je to [zde](https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html).

```python
temperatures = pandas.read_csv("temperature.csv")
teploty_vybrane = temperatures[temperatures["City"].isin(["Helsinki", "Miami Beach", "Tokyo"])]
result = temperatures.pivot_table(index='Day', columns='City',values='AvgTemperature')[['Helsinki', 'Miami Beach', 'Tokyo']]
result.plot(kind="box",whis=[0,100])
plt.show()
```

### Shrnutí

Vše super, připisuji 5 bodů :-)

**Comment by pesikj** [comment]
A lekci 5 jsi přeskočila, nebo jsi ji jen zapomněla nahrát do Gitu? :-)

**Comment by urbanovaklara** [comment]
Ahoj Jirko,

ukoly z lekce 5 jsem nestihala a myslela jsem ze je na jejich zpracovani max 14 dni tak jsem se k nim uz nevracela.

Klára

**Comment by pesikj** [comment]
V pohodě, jestli chceš, můžeš je dodělat. Ten termín je jen doporučení :-)
