### ISSUE TITLE
8.-9. lekce úkoly

### ISSUE THREAD

**Issue by urbanovaklara** [urbanovaklara/python-012021#6]
Ahoj Jirko,

prosím o kontrolu úkolů z 8. a 9. lekce.
Díky

Klára

**Comment by pesikj** [comment]
Ahoj Kláro,

obecná poznámka - v souboru `pujcovna/urls.py` máš navíc adresu `katalog/seznam/`. Zde by měl být pouze odkaz na celou aplikaci `katalog` a pokud v té aplikaci přidáš novou adresu, přidáváš ji pouze do souboru `katalog/urls.py` a nikoli do souboru `urls.py`.

### Příklad 36

Založeno je to správně :-)

### Příklad 37

Super :-)

### Příklad 38

Super :-)

### Příklad 39

Taky super :-)

### Příklad 40

Pěkně vytvořená stránka. :-)

### Příklad 41

Přidáno správně

### Příklad 42

Super :-)

### Příklad 43

Taky super :-)

### Příklad 44

Taky super 

### Příklad 45

Též správně.

### Shrnutí

Vše je správně vyřešené, připisuji 10 bodů, takže již máš dostatek bodů na udělení certifikátu, ale doufám, že bude pokračovat :-)
